### ISSUE TITLE
Not sure if working; message buffer pops up at startup

### ISSUE THREAD

**Issue by simuhyt** [PythonNut/historian.el#12]
Hello,

I am trying to use this software as follows in my .init file:
```
(use-package historian
  :ensure t
  :config
  (global-ivy-historian-mode))
```
but for some reason the *Messages* buffer will open up horizontally, splitting the window in two:
![screenshot from 2017-07-06 10-36-05](https://user-images.githubusercontent.com/29894694/27927338-6d29e872-6259-11e7-8ee0-2d5282b2ad61.png)

I am also not that sure if it is working; I use package-install a lot and it seems to take typing the whole thing for it to match.

**Comment by PythonNut** [comment]
Apologies for the delay, see the new additions to the [`README.md`](https://github.com/PythonNut/historian.el).
