### ISSUE TITLE
Which of the two start-ups is better?

### ISSUE THREAD

**Issue by yuzumx** [PythonNut/historian.el#15]
Hello：
First, I'm sorry for my poor English.

1:
```emacs-lisp
(add-hook 'after-init-hook (lambda () (ivy-historian-mode t)))
```

2:
```emacs-lisp
(ivy-historian-mode t)
```

Which is better?

Thank you.

**Comment by PythonNut** [comment]
I'm personally a fan of:

```emacs
(with-eval-after-load 'ivy
  (ivy-historian-mode t))
```

**Comment by yuzumx** [comment]
Thank you.

I've added `with-eval-after-load`, but it is at the top of the ivy setup, so I forgot to post it.

I just think, `after-init-hook` will save start-up time ... ...

However, no.
