### ISSUE TITLE
Not sure if this is working...

### ISSUE THREAD

**Issue by kuwze** [PythonNut/historian.el#17]
I am trying to get `historian.el/helm-flx-historian.el `to work and I can't tell what it does or if it is working.

Here is my relevant config:
```emacs-lisp
(use-package historian
  :ensure t
  :config
  (historian-mode 1)
  (setq helm-flx-historian-mode t))
```

**Comment by PythonNut** [comment]
Apologies for the delay, see the new additions to the [`README.md`](https://github.com/PythonNut/historian.el).
