### ISSUE TITLE
Can not add directory locale variables when ivy-historian is enabled

### ISSUE THREAD

**Issue by yuzumx** [PythonNut/historian.el#18]
Hello:

First, I'm sorry for my poor English.

I am a Emacs rookie. After enabling ivy-historian, Emacs tells me the parameter is wrong when I add some directory locale variables using `M-x add-dir-local-variable`:
```
historian-push-item: Wrong type argument: stringp, 4
```

Screenshot:
<img width="1280" alt="2" src="https://user-images.githubusercontent.com/26828933/37073817-18118456-2204-11e8-9587-fa90208de1a0.png">
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/26828933/37073828-1f660dc6-2204-11e8-9f9f-28d1d2b3a20c.png">
<img width="1280" alt="3" src="https://user-images.githubusercontent.com/26828933/37073833-238a2a18-2204-11e8-8aec-5a59f0635185.png">

When I disabled `ivy-historian-mode` and `historian-mode`, Everything returned to normal.

My `ivy-historian` config:
```emacs-lisp
(when (package-installed-p 'ivy-historian)
  (ivy-historian-mode t))
```
My emacs version is `25.3`

Thank you very much.

**Comment by PythonNut** [comment]
Apologies for the delay, see the new additions to the [`README.md`](https://github.com/PythonNut/historian.el). If those don't work, let me know and I'll try to reproduce the issue.

**Comment by yuzumx** [comment]
Thank you!

But those don't work...

The error message is too long, so paste it here as a file.
[error.txt](https://github.com/PythonNut/historian.el/files/2091863/error.txt)

**Comment by PythonNut** [comment]
Ah I have reproduced something similar to this. I'll get on it as soon as I have some free time.

**Comment by yuzumx** [comment]
Thank you very much~
