### ISSUE TITLE
Replacement for company-statistics?

### ISSUE THREAD

**Issue by raxod502** [PythonNut/historian.el#7]
This is a speculative issue.

I was wondering if `historian.el` would be easily extensible to also support recording history for `company-mode` selections. If that were the case, then the functionality of `company-statistics` could be subsumed into this package to provide a more uniform interface.

**Comment by PythonNut** [comment]
Yes, this is definitely possible.

This could also resolve the problem where `company-statistics` cannot be used with `company-flx`. 

This shouldn't be very difficult, as a lot of work has already been done in `company-statistics`.

**Comment by raxod502** [comment]
No longer necessary for me since I created https://github.com/raxod502/prescient.el which both replaces `historian.el` and subsumes `company-statistics`.
