### ISSUE TITLE
historian-load: Odd number of elements in hash table data

### ISSUE THREAD

**Issue by manuel-uberti** [PythonNut/historian.el#8]
Hi,

thanks for this package. I don't know whether it depends on recent `ivy` updates, but since this morning I can't use `ivy-historian` anymore.

When I try to enable it with `(ivy-historian-mode +1)`, I get this message:

`historian-load: Odd number of elements in hash table data`

**Comment by PythonNut** [comment]
Have you tried (backing up and) deleting the historian save file?

**Comment by manuel-uberti** [comment]
Thank you, that seems to work.

**Comment by s-kostyaev** [comment]
@PythonNut looks like you rich `print-length` limit while print history to `.historian`. Use 
```elisp
(let ((print-length nil)) 
  ...
```
before add elements to history file.

**Comment by PythonNut** [comment]
@s-kostyaev any chance you can make a PR? If not, I can probably get to it this weekend or so.

**Comment by s-kostyaev** [comment]
@PythonNut maybe. Don't know if I will have the time.
